/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-30 04:16:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.Console;
import jdk.internal.misc.FileSystemOption;
import com.jkb.yanolja.domain.config.DBConnection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1611639769400L));
    _jspx_dependants.put("jar:file:/D:/Programming/yanolja/yanoljaa/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yanolja/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/header/header.jsp", Long.valueOf(1611980093275L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jdk.internal.misc.FileSystemOption");
    _jspx_imports_classes.add("com.jkb.yanolja.domain.config.DBConnection");
    _jspx_imports_classes.add("java.io.Console");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>야놀자</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index/index_style.css?ver=1\"  media=\"all\" type=\"text/css\"/>\r\n");
      out.write("      \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <!--캘린더-->\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.8/js/solid.js\" integrity=\"sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js\" integrity=\"sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js\"></script> \r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js\"></script> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css\" /> \r\n");
      out.write("   <!--캘린더 끝-->\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"between yanolja \">\r\n");
      out.write("            <div class=\"yanolja__empty  \"></div>\r\n");
      out.write("            <div class=\"yanolja__yanolja  \">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"HomeTitle_logo__14aI3\">\r\n");
      out.write("                    <img src=\"//yaimg.yanolja.com/joy/sunny/static/images/logo.svg\"\r\n");
      out.write("                        alt=\"야놀자 웹사이트. 최저가 모텔, 호텔, 종합 숙박, 대한민국 대표 숙소 예약사이트, 야놀자 숙박 어플\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"section__header \">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section1__main \">\r\n");
      out.write("            <div class=\"section1__header \">\r\n");
      out.write("                <div class=\"\"></div>\r\n");
      out.write("                <div class=\"section1__header__text\"><img src=\"images/index/arrow.png\">서울특별시 강남구 대치동1 🌏</div>\r\n");
      out.write("                <div class=\"\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"section1__body \">\r\n");
      out.write("                <div></div>\r\n");
      out.write("                <div class=\"section1__body__main \">\r\n");
      out.write("                    <div class=\"section1__body__line \">\r\n");
      out.write("                        <div class=\"section1__line__box \"><a class = \"link__common\" href=\"motelArea\">\r\n");
      out.write("                            <div class=\"section1__box__image \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f96123d4927a4.64705409.png\"\r\n");
      out.write("                                    alt=\"모텔\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>모텔</p>\r\n");
      out.write("                            </div></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f96126eebabc9.82379506.png\"\r\n");
      out.write("                                    alt=\"호텔\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>호텔</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f9612f3c50b28.73087146.png\"\r\n");
      out.write("                                    alt=\"프리미엄호텔\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>프리미엄 호텔</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f961322ddb2e2.01605949.png\"\r\n");
      out.write("                                    alt=\"펜션/풀빌라\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>펜션/풀빌라</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f9613582a8a64.27167401.png\"\r\n");
      out.write("                                    alt=\"레저/티켓\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>레저/티켓</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section1__body__line \">\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/15/14/5ebe29c57cde91.51112609.png\"\r\n");
      out.write("                                    alt=\"글램핑/캠핑\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>글램핑/캠핑</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd0478e3ed72.62476270.png\"\r\n");
      out.write("                                    alt=\"리조트/콘도\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>리조트/콘도</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2019/06/24/12/5d10489ac92502.65078667.png\"\r\n");
      out.write("                                    alt=\"게하/한옥\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>게하/한옥</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd076b422a65.77359130.png\"\r\n");
      out.write("                                    alt=\"해외숙소\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>해외숙소</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd0584221724.08469882.png\"\r\n");
      out.write("                                    alt=\"항공권\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>항공권</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section1__body__line \">\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/01/08/12/5e154959aa0c87.14563710.png\"\r\n");
      out.write("                                    alt=\"KTX\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>KTX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd05a3422175.02655598.png\"\r\n");
      out.write("                                    alt=\"렌터카\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>렌터카</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/12/08/15/5fcf1ee99255b9.43495013.png\"\r\n");
      out.write("                                    alt=\"모바일교환권\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>모바일교환권\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/10/26/13/5f965234141fb4.53399957.png\"\r\n");
      out.write("                                    alt=\"아이야놀자\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>아이야놀자</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/10/05/10/5f7a7ddc950d05.04955218.png\"\r\n");
      out.write("                                    alt=\"강원도야놀자\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>강원도야놀자</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section1__body__line \">\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f9614e21039c8.23417181.png\"\r\n");
      out.write("                                    alt=\"호캉스패키지\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>호캉스패키지</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/12/10/17/5fd1dbfb8899a6.02661515.png\"\r\n");
      out.write("                                    alt=\"스파펜션\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>스파펜션</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/11/06/16/5fa4fb175fd6e7.26002401.png\"\r\n");
      out.write("                                    alt=\"모텔의재발견\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>모텔의재발견</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/10/26/09/5f9615a239e323.11884805.png\"\r\n");
      out.write("                                    alt=\"무한대실\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>무한대실</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/10/05/10/5f7a7c721c0469.82434291.png\"\r\n");
      out.write("                                    alt=\"더보기\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">\r\n");
      out.write("                                <p>더보기</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section1__body__line__last  \">\r\n");
      out.write("                        <div class=\"section1__line__box__last  \">\r\n");
      out.write("                            <div class=\"section1__box__image  \">\r\n");
      out.write("                                <img src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd08056519c5.95575485.png\"\r\n");
      out.write("                                    alt=\"선착순쿠폰\" width=\"50px\" height=\"50px\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"section1__box__text \">선착순 쿠폰</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box__last sideBorder \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2020/05/14/17/5ebd08233e0894.58373980.png\"\r\n");
      out.write("                                    alt=\"무한쿠폰룸\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">무한쿠폰룸</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"section1__line__box__last \">\r\n");
      out.write("                            <div class=\"section1__box__image \"><img\r\n");
      out.write("                                    src=\"https://yaimg.yanolja.com/v5/2021/01/20/11/60078ffe4f7e12.97310328.png\"\r\n");
      out.write("                                    alt=\"2월얼리버드\" width=\"50px\" height=\"50px\"></div>\r\n");
      out.write("                            <div class=\"section1__box__text \">2월얼리버드</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"section2__main\">\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div class=\"section2__main__center \">\r\n");
      out.write("                <div class=\"section2__banner1\">\r\n");
      out.write("                    <img src=\"images/index/banner1.png\" alt=\"배너\" width=\"750px\" height=\"60px\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div id=\"demo\" class=\"carousel slide section2__slide mt10\" data-ride=\"carousel\">\r\n");
      out.write("                        <ul class=\"carousel-indicators\">\r\n");
      out.write("                            <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                            <li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("                            <li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"carousel-inner\">\r\n");
      out.write("                            <div class=\"carousel-item active\">\r\n");
      out.write("                                <img src=\"images/index/section2_1.png\" alt=\"Los Angeles\" width=\"770px\" height=\"100px\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"images/index/section2_2.png\" alt=\"Chicago\" width=\"770px\" height=\"100px\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"images/index/section2_3.png\" alt=\"New York\" width=\"770px\" height=\"100px\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("                            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("                            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"section2__banner3 mt10\">\r\n");
      out.write("                        <div class=\"banner3__search font__subtitle\">회원 인기 검색어</div>\r\n");
      out.write("                        <div class=\"banner3__img\">\r\n");
      out.write("                            <div><img src=\"images/index/banner3_1.png\" alt=\"배너\" width=\"750px\" height=\"60px\" /></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner3_2.png\" alt=\"배너\" width=\"750px\" height=\"60px\" /></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner3_3.png\" alt=\"배너\" width=\"750px\" height=\"60px\" /></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner3_4.png\" alt=\"배너\" width=\"750px\" height=\"60px\" /></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner3__hashtag mt10\">\r\n");
      out.write("                            <div class=\"banner3__hashtag__text border\">#인기숙소</div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text border\">#무료영화</div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text border\">#스파펜션</div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text\"></div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text\"></div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text\"></div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text\"></div>\r\n");
      out.write("                            <div class=\"banner3__hashtag__text\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"section2__banner4 mt10 pr10 pl10\">\r\n");
      out.write("                        <div class=\"banner4__hocance pt10\">\r\n");
      out.write("                            <div class=\"banner4__hocance__text font__subtitle\" id=banner4__hocance__text>우리도 호캉스 갈까?\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div></div>\r\n");
      out.write("                            <div class=\"banner4__hocance__link  \"><button type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("                                    id=\"banner4__hocance__link\">호텔 리조트</button></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <form>\r\n");
      out.write("                                <div class=\"banner4__buttonList tbBorder mt10 \">\r\n");
      out.write("                                    <div><button type=\"button\" id=\"banner4__button1\" class=\"banner4__button\"\r\n");
      out.write("                                            onclick=\"changeImage1A()\">서울</button></div>\r\n");
      out.write("                                    <div><button type=\"button\" id=\"banner4__button2\" class=\"banner4__button\"\r\n");
      out.write("                                            onclick=\"changeImage2A()\">경기인천</button></div>\r\n");
      out.write("                                    <div><button type=\"button\" id=\"banner4__button3\" class=\"banner4__button\"\r\n");
      out.write("                                            onclick=\"changeImage3A()\">강원</button></div>\r\n");
      out.write("                                    <div><button type=\"button\" id=\"banner4__button4\" class=\"banner4__button\"\r\n");
      out.write("                                            onclick=\"changeImage4A()\">부산</button></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"banner4__imgs mt10\">\r\n");
      out.write("                                    <div class=\"banner4__img \"><img id=\"banner4_img1\" src=\"\"\r\n");
      out.write("                                            alt=\"배너\" /></div>\r\n");
      out.write("                                    <div class=\"banner4__img \"><img id=\"banner4_img2\" src=\"\"\r\n");
      out.write("                                            alt=\"배너\" /></div>\r\n");
      out.write("                                    <div class=\"banner4__img \"><img id=\"banner4_img3\" src=\"\"\r\n");
      out.write("                                            alt=\"배너\" /></div>\r\n");
      out.write("                                    <div class=\"banner4__img \"><img id=\"banner4_img4\" src=\"\"\r\n");
      out.write("                                            alt=\"배너\" /></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"banner4__info\">\r\n");
      out.write("                                    <div class=\"banner4__info__text\" id=\"banner4_text1\">페어필드 바이 메리어트 서울</div>\r\n");
      out.write("                                    <div class=\"banner4__info__text\" id=\"banner4_text2\">신라스테이 구로</div>\r\n");
      out.write("                                    <div class=\"banner4__info__text\" id=\"banner4_text3\">신라스테이 삼성</div>\r\n");
      out.write("                                    <div class=\"banner4__info__text\" id=\"banner4_text4\">호텔포코</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"banner4__price \">\r\n");
      out.write("                                    <div class=\"banner4__info__price\"><strong id=\"banner4__price1\">59,900</strong>원\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"banner4__info__price\"><strong id=\"banner4__price2\">60,500</strong>원\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"banner4__info__price\"><strong id=\"banner4__price3\">97,450</strong>원\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"banner4__info__price\"><strong id=\"banner4__price4\">79,000</strong>원\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pt10\">\r\n");
      out.write("                            <div class=\"banner4__other_theme\"><button type=\"button\" id=\"banner4__toggle\"\r\n");
      out.write("                                    onclick=\"banner4__toggle()\">\r\n");
      out.write("                                    <img src=\"//yaimg.yanolja.com/joy/sunny/static/images/home-refresh.svg\" /> 다른 테마 보기\r\n");
      out.write("                                    <strong id=\"banner4__page\">1</strong> / 2\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"section2__banner5 mt10 pl10\">\r\n");
      out.write("                    <div class=\"banner5__main\">\r\n");
      out.write("                        <div class=\"banner5__text\">\r\n");
      out.write("                            <div class=\"font__subtitle pt10\">\r\n");
      out.write("                                이세상 모든 놀거리\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"banner5__sub__text\">\r\n");
      out.write("                                레저 초특가 No.1 야놀자\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner5__leisure__btn\"><button type=\"button\" class=\"btn btn-outline-primary \">레저/티켓</button></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"banner5__imgs mt10\">\r\n");
      out.write("                                <div class=\"banner5__img \"><img id=\"banner5_img1\" src=\"\"\r\n");
      out.write("                                        alt=\"배너\" /></div>\r\n");
      out.write("                                <div class=\"banner5__img \"><img id=\"banner5_img2\" src=\"\"\r\n");
      out.write("                                        alt=\"배너\" /></div>\r\n");
      out.write("                                <div class=\"banner5__img \"><img id=\"banner5_img3\" src=\"\"\r\n");
      out.write("                                        alt=\"배너\" /></div>\r\n");
      out.write("                                <div class=\"banner5__img \"><img id=\"banner5_img4\" src=\"\"\r\n");
      out.write("                                        alt=\"배너\" /></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"banner5__info\">\r\n");
      out.write("                                <div class=\"banner5__info__text\" id=\"banner5_text1\">ㅁ</div>\r\n");
      out.write("                                <div class=\"banner5__info__text\" id=\"banner5_text2\">ㅁ</div>\r\n");
      out.write("                                <div class=\"banner5__info__text\" id=\"banner5_text3\">ㅁ</div>\r\n");
      out.write("                                <div class=\"banner5__info__text\" id=\"banner5_text4\">ㅁ</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"banner5__price \">\r\n");
      out.write("                                <div class=\"banner5__info__price\"><strong id=\"banner5__price1\">ㅁ</strong>원\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"banner5__info__price\"><strong id=\"banner5__price2\">ㅁ</strong>원\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"banner5__info__price\"><strong id=\"banner5__price3\">ㅁ</strong>원\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"banner5__info__price\"><strong id=\"banner5__price4\">ㅁ</strong>원\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"banner5__other_theme\"><button type=\"button\" id=\"banner5__toggle\"\r\n");
      out.write("                            onclick=\"banner5__toggle()\">\r\n");
      out.write("                            <img src=\"//yaimg.yanolja.com/joy/sunny/static/images/home-refresh.svg\" /> 다른 테마 보기\r\n");
      out.write("                            <strong id=\"banner5__page\">1</strong> / 2\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"section2__banner6 pl10 mt10\">\r\n");
      out.write("                    <div class=\"font__subtitle pt10\">기획전</div>\r\n");
      out.write("                    <div class=\"banner6__imgs mt10 \">\r\n");
      out.write("                        <div class=\"banner6__imgs__lr rBorder \">\r\n");
      out.write("                            <div><img src=\"images/index/banner6_1.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_2.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_3.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_4.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_5.png\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner6__imgs__lr \">\r\n");
      out.write("                            <div><img src=\"images/index/banner6_6.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_7.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_8.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_9.png\"/></div>\r\n");
      out.write("                            <div><img src=\"images/index/banner6_10.png\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                    <div class=\"banner6_btn mt10\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary\">더 다양한 기획전 보기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div class=\"footer__main__center mt10\">\r\n");
      out.write("                <div class=\"footer__top\"><strong>[공지사항]</strong>야놀자 개인정보처리방침 개정 안내 (2020. 11.30)</div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"footer__center1 mt10\">\r\n");
      out.write("                        <div class=\"footer__left\">yanolja</div>\r\n");
      out.write("                        <div class=\"footer__right\">패밀리 사이트</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer__info mt10\">\r\n");
      out.write("                        <div>(주)야놀자 |대표이사 : 이수진 | 사업자 등록번호 : 220-87-42885 | 통신판매업신고 : 강남-14211호 | 메일 : help@yanolja.com</div>\r\n");
      out.write("                        <div>관광사업자 등록번호 : 제2016-31호 | 주소 : 서울 강남구 테헤란로 108길 42 | 호스팅서비스 제공자 : 주식회사 야놀자</div>\r\n");
      out.write("                        <div>고객센터 : 1644-1346 (오전 9시 - 익일 새벽 3시)</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer__buuton mt10\">\r\n");
      out.write("                        <div><button>회사소개</button></div>\r\n");
      out.write("                        <div><button>광고제휴문의</button></div>\r\n");
      out.write("                        <div><button>인재채용</button></div>\r\n");
      out.write("                        <div><button>개인정보처리방침</button></div>\r\n");
      out.write("                        <div><button>청소년 보호 정책</button></div>\r\n");
      out.write("                        <div><button>서비스 이용약관</button></div>\r\n");
      out.write("                        <div><button>위치정보이용약관</button></div>\r\n");
      out.write("                        <div><button>사업자 정보확인</button></div>\r\n");
      out.write("                        <div class=\"footer__empty\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer_icons mt10\">\r\n");
      out.write("                        <div class=\"footer_icon\"><img src=\"images/index/footer_icon1.png\"/></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                        <div></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer__center__last mt10\">(주) 야놀자는 통신판매 중개자로서 통신판매의 당사자가 아니며 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer__bottom\"><img src=\"images/index/footer_banner1.png\"/></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"javascript/index.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /header/header.jsp(29,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"yanolja__user  \">\r\n");
          out.write("                <div>\r\n");
          out.write("                    <button type=\"button\" class=\"btn\"  onclick = \"location.href = 'login'\">로그인</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div>\r\n");
          out.write("                <button type=\"button\" class=\"btn\" onclick = \"location.href = 'join'\">회원가입</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /header/header.jsp(39,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             <div class=\"yanolja__user  \">\r\n");
          out.write("                <div>\r\n");
          out.write("                 <form action=\"/yanolja/reservationList\" method=\"post\" id=\"reservation_list\" >\r\n");
          out.write("                 <input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" name=\"reservation_input\" id=\"reservation_input\" />\r\n");
          out.write("                 <input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" name=\"reservation_username\" id=\"reservation_username\" />\r\n");
          out.write("                    <button type=\"submit\" class=\"btn\"  >예약 리스트보기</button>\r\n");
          out.write("                    </form>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div>\r\n");
          out.write("                <button type=\"button\" class=\"btn\" onclick = \"location.href = 'logout'\">로그아웃</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }
}
