/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-28 08:37:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class motelArea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1611639769400L));
    _jspx_dependants.put("jar:file:/D:/Programming/yanolja/yanoljaa/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yanolja/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/header/header.jsp", Long.valueOf(1611823041276L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>모텔 지역 선택</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/motelArea/motelArea_style.css\" />\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <!--캘린더-->\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.8/js/solid.js\" integrity=\"sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js\" integrity=\"sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js\"></script> \r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js\"></script> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css\" /> \r\n");
      out.write("   <!--캘린더 끝-->\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"between yanolja \">\r\n");
      out.write("            <div class=\"yanolja__empty  \"></div>\r\n");
      out.write("            <div class=\"yanolja__yanolja  \">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"HomeTitle_logo__14aI3\">\r\n");
      out.write("                    <img src=\"//yaimg.yanolja.com/joy/sunny/static/images/logo.svg\"\r\n");
      out.write("                        alt=\"야놀자 웹사이트. 최저가 모텔, 호텔, 종합 숙박, 대한민국 대표 숙소 예약사이트, 야놀자 숙박 어플\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"section__main\">\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div class=\"section__center\">\r\n");
      out.write("                <div class=\"section__first\"><img src=\"images/motelArea/section_first.png\" /></div>\r\n");
      out.write("                <div class=\"section__second\">\r\n");
      out.write("                    <div class=\"second__title  pr20 pl20 pt10 \">\r\n");
      out.write("                        <div>지역선택</div>\r\n");
      out.write("                        <div><button type=\"button\" class=\"btn btn-outline-primary\">🌏 내 주변</button></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"area__list\">\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            서울\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">서울<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"motelList_Gangnam\">강남/역삼/삼성/논현</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">서초/신사/방배</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">잠실/신천(잠실새내)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">영등포/여의도</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">신림/서울대/사당/동작</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">천호/길동/둔촌</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">화곡/까치산/양천/목동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">구로/금천/오류/신도림</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">신촌/홍대/합정</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">연신내/불광/용암</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">종로/대학로/동묘앞역</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">성신여대/성북/월곡</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">이태원/용산/서울역/명동/회현</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">회기/고려대/청량리/신설동</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">건대/군자/구의</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">왕십리/성수/금호</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">수유/미아</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">상봉/중랑/면목</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">태릉/노언/도봉/창동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            경기\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">경기<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">수원 인계/권선/영통</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">수원역/구운/장안/세류</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">안양/평촌/인덕원/과천</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">성남/분당/위례</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">용인</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">안산</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">군포/의왕/금정/산본</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">시흥</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">광명</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">평택/송탄/안성</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">부천</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">일산/고양</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">파주</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">김포</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">의정부</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">구리</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">남양주</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">포천</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">양주/동두천/연천</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">양평</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">가평/청평</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">제부도/대부도</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            인천\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">인천<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">부평</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">구월</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">서구(석남,서구청,검단)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">계양(작전,경인교대)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">즈인</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">송도/연수</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">인천공항/을왕리</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">중구(월미도/차이나타운/신포/동인천)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">강화/옹진</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동암/간석</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">남동구(소래/만수)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">용현/숭의/도화/동구</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            강원\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">강원<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">춘천/강촌</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">원주</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">경포대/사천/주문진/정동진</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">강릉역/교동/옥계</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">영월/정선</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">속초/고성</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">양양(서피비치/낙산)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동해/삼척/태백</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">평창</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">홍천/횡성</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">화천/철원/인제/양구</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            제주\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color\">\r\n");
      out.write("                                            <div class=\"dropdown__double \">\r\n");
      out.write("                                                <div class=\"dropdown__line  \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">제주<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">제주시</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">서귀포시</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">하귀/애월/한림/협재</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            대전\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">대전<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">유성구</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">중구(은행/대흥/선화/유천)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동구(용전/복합터미널)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">서구(둔산/용문/월평)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">대덕구(중리/신탄진)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                        충북\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">충북<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">청주 흥덕구 / 서원구 (청주 터미널)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">청주 상당구/ 청원구 (청주국제공항)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">충주/수안보</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">제천/진천/음성/단양</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">보은/옥천/괴산/증평/영동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            충남/세종\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">충남/세종<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">천안 서북구</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">천안 동남구</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">아산</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">공주/동학사/세종</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">계룡/금산/논산/청양</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">예산/홍성</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">태안/안면도/서산</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">당진</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">보령/대천해수욕장</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">서천/부여</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            부산\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">부산<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">해운대/센텀시티/재송</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">송정/기장/정관</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">광안리/수영</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">경성대/대연/용호동/문현</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"motelList_Seomyeon\">서면/양정/초읍/부산시민공원</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">남포동/중앙동/태종대/송도/영도</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">부산역/범일역/부산진역</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">연산/토곡</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동래/사직/온천장/부산대/구서</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">사상(경전철)/엄궁/학장</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">덕천/화명/만덕/구포(구포역/KTX역)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">하단/명지/김해공항/다대포/강서/신호/괴정/지사</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            울산\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">울산<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">남구/중구(삼산/성남/무거/신정)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동구/북구/을주군(일산/진장/진하/KTX역/영남알프스)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            경남\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">경남<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">창원 상남동/용호동/중앙동/창원시청</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">창원 명서동/봉곡동/팔용동/북면온천/창원종합버스터미널</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">마산/진해</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">김해/장유</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">양산/밀양</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">진주</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">거제/통영/고성</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">사천/남해</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">하동/산청/함양</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">거창/함안/창녕/합천/의령</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            대구\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">대구<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동성로/서문시장/대구시청/삼덕동/교동/종로</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">대구역/칠성시장/경북대/엑스코/칠곡지구/태전동/금호지구</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">동대구역/고속버스터미널/신천동/신암동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">대구공항/혁신도시/동촌유원지/팔공산/이시아폴리스</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">수성못/범어/라이온즈파크/월드컵경기장/앞산공원/대명동/봉덕동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">북부정류장/이현공단/평리동/내당동/비산동/원대동</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">두류공원/이월드/광장코아/서부정류장/본리동/죽전동</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">성서/계명대/성서공단/상인동/달성군/가창/현풍/논공</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            경북\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">경북<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">포항/남구(시청/시외버스터미널/구룡포/쌍사/문덕/오천)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">포항/북구(영일대/죽도시장/여객터미널/송도)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">경주(보문단지/황리단길/불국사/양남/감포/안강)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">구미</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">경산(영남대/대구대/갓바위/하양/진량/자인)</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">안동(경북도청/하회마을)</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">영천/청도</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">김천/칠곡/성주</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">문경/상주/영주/예천/군위/의성/봉화</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">울진/영덕/청승</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">울릉도</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            광주\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">광주<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">상무지구/금호지구/유스퀘어/서구</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">첨단지구/하남지구/송정역/광산구</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">충장로/대인시장/국립아시아문화전당/동구/남구</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">광주역/기아챔피언스필드/전대사거리/북구</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"area__line\">\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            전남\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-left dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">전남<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">여수</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">순천</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">광양</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">목포/무안/영암/신안</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">나주/함평/영광/장성</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">담양/곡성/화순/구례</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">해남/완도/진도/강진/장흥/보성/고흥</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"area__solo\">\r\n");
      out.write("                                <div class=\"container dropdown__padding\">\r\n");
      out.write("                                    <div class=\"dropdown bBorder\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn dropdown-toggle dropdown__size\"\r\n");
      out.write("                                            data-toggle=\"dropdown\">\r\n");
      out.write("                                            전주/전북\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right dropdown__color \">\r\n");
      out.write("                                            <div class=\"dropdown__double\">\r\n");
      out.write("                                                <div class=\"dropdown__line \">\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header\"><span class=\"dropdown__point1\">전주/전북<span class=\"dropdown__point2\"> TOP</span>숙소</span></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"dropdown__header bBorder\">\r\n");
      out.write("                                                        <h5 class=\"dropdown-header \"></h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">전주/완주</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">군산</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">익산</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">남원/임실/순창/무주/진안/장수</a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"dropdown__line\">\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\">정읍/부안/김제/고창</a></div>\r\n");
      out.write("                                                    <div><a class=\"dropdown-item\" href=\"#\"></a></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section__third mt20\"><img src=\"images/motelArea/section_third.png\"/></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 4번째 남는 div남겨둠-->\r\n");
      out.write("                <div></div>\r\n");
      out.write("                <!-- 4번째 남는 div남겨둠 끝-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /header/header.jsp(29,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"yanolja__user  \">\r\n");
          out.write("                <div>\r\n");
          out.write("                    <button type=\"button\" class=\"btn\"  onclick = \"location.href = 'login'\">로그인</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div>\r\n");
          out.write("                <button type=\"button\" class=\"btn\" onclick = \"location.href = 'join'\">회원가입</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /header/header.jsp(39,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.session !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             <div class=\"yanolja__user  \">\r\n");
          out.write("                <div>\r\n");
          out.write("                    <button type=\"button\" class=\"btn\"  onclick = \"location.href = '#'\">예약 리스트보기</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div>\r\n");
          out.write("                <button type=\"button\" class=\"btn\" onclick = \"location.href = 'logout'\">로그아웃</button>\r\n");
          out.write("            </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }
}
